name: Dev Code Deployment
run-name: ${{ github.actor }}  developer is pushing the code , then test cases will execute
on: 
  push:
  workflow_dispatch:
jobs:
  Run_Test_Cases_As_Part_Of_Develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout_To_Testcases_Repoo
        uses: actions/checkout@v3
        with:
            repository: iqrabibi/GithubActionPractice
            token: ${{ secrets.MYPAT }} 
            path: iqrabibi/GithubActionPractice

            #// in case private repo and on other github
      - run: npm install
      - run: npm run run_test_cases