name: Dev Code Deployment
run-name: ${{ github.actor }}  developer is pushing the code , then test cases will execute
on: 
  push:
  workflow_dispatch:
jobs:
  Run_Test_Cases_As_Part_Of_Developed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout_To_Testcases_Repository
        uses: actions/checkout@v3
        with:
          repository: iqrabibi/GithubActionPractice
          token: ${{ secrets.MY_PAT}} 
            #// in case private repo and on other github
      - run: npm install
      - run: npm run run_test_cases

      - name: Send_mail
        if: always()
        uses: dawidd6/action-send-mail@v2
        with:
      # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
      # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
      # email subject
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
      # email body as text
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
      # comma-separated string, send email to
          to: iqrabibi25@yahoo.com,iqra.bibi@venturedive.com
      # from email name
          from: ${{ github.actor }}