name: Dev Code Deployment
run-name: ${{ github.actor }}  developer is pushing the code , then test cases will execute
on: 
  push:
  workflow_dispatch:
jobs:
  Run_Test_Cases_As_Part_Of_Develop:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v3
         with:
          repository: iqrabibi/GithubActionPractice
          # token: ${{ secrets.my_pat }}
      - run: npm install
      - run: npm run run_test_cases